name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set environment variables
        run: |
          echo "UPDATGAME=${{ secrets.UPDATGAME }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build

