name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17.0.7
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.7'
          distribution: 'adopt'

      - name: Set environment variables
        run: echo "UPDATGAME=${{ secrets.UPDATGAME }}"

      - name: Build with Gradle
        run: ./gradlew wrapper

